#!/usr/bin/env bash
# Verifica anonimato do repo Hefesto - Dualsense4Unix.
# Exit 0 se limpo, exit 1 se houver violação.
# Estratégia: regex completa + whitelist de arquivos (não de palavras).

set -euo pipefail

# Termos proibidos. \b garante palavra inteira onde aplicável.
#
# ANONIMATO-FALSO-POSITIVO-OPUS-01: `opus` NÃO entra sozinho na lista. Opus é
# o codec de áudio da IETF (RFC 6716) — é o que o DualSense usa para o mic e o
# fone por Bluetooth, então a palavra é vocabulário técnico obrigatório aqui.
# Barrá-la reprovava código legítimo e empurrava para eufemismo, que é pior
# para quem for ler o protocolo depois. O uso que o gate quer barrar é o de
# NOME DE MODELO, e esse vem sempre acompanhado — `claude` continua na lista e
# pega "Claude Opus" inteiro.
#
# ANONIMATO-FRONTEIRA-DE-PALAVRA-01 (30/07): `feito por` e `criado por` estavam
# SEM `\b` inicial e casavam DENTRO de outra palavra. O caso medido:
# "o de|feito por|que" — a frase "o defeito porque..." reprovava o repositório
# inteiro. Pior, o defeito só aparecia DEPOIS do `git add`, porque o gate usa
# `git grep` e é cego a arquivo não rastreado; o commit f319c6f entrou vermelho
# por causa disso. O `\b` inicial resolve sem afrouxar nada: "feito por uma IA"
# continua reprovando, "defeito porque" passa.
FORBIDDEN='(\b(claude|anthropic|openai|chatgpt|sonnet|haiku|gemini|copilot|mistral|grok)\b|\bclaude[- ]opus\b|gpt-?[0-9]+|\bllama[- ]?[0-9]|\bby (claude|ai|gpt|an ai)\b|(ai|machine)-generated|generated by (an? )?(ai|llm|model)|\bfeito por\b|\bcriado por\b|autor:\s|made by|written by|credit to)'

# Arquivos/paths excluídos do check. Processo/história, não código.
EXCLUDE_PATHSPECS=(
    ':!LICENSE'
    ':!NOTICE'
    # ANONIMATO-TEXTO-DE-LICENCA-01 (07/08/2026): a CR-05 trouxe para a árvore o
    # texto CANÔNICO da GPL-2.0 (LICENSES/GPL-2.0.txt), porque a GPL, seção 1,
    # exige que a cópia da licença acompanhe o fonte — e cinco alvos de
    # empacotamento distribuem os fontes GPL de assets/dkms/. O texto da FSF
    # casa o regex em TRÊS linhas, todas falso positivo do padrão `made by`:
    #
    #   :76  "...independent of having been made by running the Program)."
    #   :166 "If distribution of executable or object code is made by offering"
    #   :330 "`Gnomovision' (which makes passes at compilers) written by James
    #         Hacker."  (o exemplo de aviso de copyright que a própria GPL dá)
    #
    # Não há correção possível do lado do arquivo: licença editada é licença
    # outra, e a regra da casa é que não se inventa nem se ajusta texto de
    # licença. A exclusão é a mesma classe da do LICENSE e da do NOTICE logo
    # acima — texto jurídico de terceiro, não código nosso.
    #
    # A exclusão é ESTREITA de propósito: só os `.txt`, que são os textos
    # canônicos. O `LICENSES/README.md`, que é prosa NOSSA, continua dentro do
    # portão. E os `.txt` não viram esconderijo porque
    # tests/unit/test_cr05_licencas_de_terceiros_viajam.py fixa o
    # `LICENSES/GPL-2.0.txt` por SHA-256: qualquer byte a mais reprova a suíte.
    ':!LICENSES/*.txt'
    ':!CHANGELOG.md'
    ':!VALIDATOR_BRIEF.md'
    ':!.gitignore'
    ':!docs/process/**'
    ':!docs/history/**'
    ':!tests/fixtures/**'
    ':!tests/unit/test_check_anonymity.py'
    ':!.git/**'
    ':!scripts/check_anonymity.sh'
    # Detector irmão: contém os mesmos regexes (anthropic|openai|claude|...)
    # como parte da própria checagem — auto-referência, não violação.
    ':!.github/workflows/anonymity-check.yml'
)

# Usa a LISTA do git + grep se estivermos em repo (respeita .gitignore +
# pathspec). Cai pra grep manual se repo ainda não inicializado (W0.1 pré-git
# init).
if git rev-parse --git-dir >/dev/null 2>&1; then
    # ANONIMATO-CEGO-A-ARQUIVO-NOVO-01 (13/08/2026): aqui era `git grep`, e
    # `git grep` só enxerga o que está no ÍNDICE. Arquivo recém-escrito, ainda
    # sem `git add`, passava VERDE — o portão calava exatamente no arquivo que
    # ninguém tinha revisado, que é quando o deslize entra. O comentário da
    # ANONIMATO-FRONTEIRA-DE-PALAVRA-01, lá em cima, já registrava a cegueira
    # ("o defeito só aparecia DEPOIS do `git add`, porque o gate usa `git grep`
    # e é cego a arquivo não rastreado; o commit f319c6f entrou vermelho por
    # causa disso") e ninguém a tinha curado: este era o ÚLTIMO portão cego da
    # casa. `validar-acentuacao.py` (listar_arquivos_git) e `validar-glifos.py`
    # (idem) já fazem o mesmo desde a PORTÃO-VIVO-01 Bloco A.
    #
    # A cura é trocar a BUSCA pela LISTA: `git ls-files --cached --others
    # --exclude-standard` traz o rastreado E o novo, sem trazer o ignorado, e o
    # grep varre a lista. Os pathspecs de exclusão continuam valendo letra por
    # letra — `git ls-files` lê a mesma sintaxe `:!` do `git grep`.
    #
    # MEDIDO em 13/08/2026, num repo de mentira: com o `git grep`, um
    # `src/.../novo.py` contendo "# by claude" e NUNCA adicionado devolvia
    # "OK: anonimato preservado." e exit 0.
    #
    # ANONIMATO-MAIUSCULA-01 (13/08/2026) — ACHADO, MEDIDO, E DEIXADO DE PÉ,
    # porque consertá-lo é decisão dela e não do portão:
    #
    # o grep daqui NÃO leva `-i`, e a regex acima é toda minúscula. Logo, no
    # ramo do git, maiúscula é esconderijo: um arquivo RASTREADO com "escrito
    # com Claude Opus" passa verde (medido num repo de mentira em 13/08/2026).
    # O `-i` existia (`git grep -niE`, commit 9cbfcc0) e sumiu em c51c902,
    # quando o `-I` do parágrafo abaixo entrou NO LUGAR do `i` em vez de ao
    # lado dele. A suíte não viu porque o teste que cobre esse caso
    # (`test_ainda_pega_o_modelo_composto`) exercita o ramo de FALLBACK, que
    # nunca perdeu o `-i`.
    #
    # O PREÇO DE DEVOLVER O `-i`, medido na árvore de 13/08/2026: 25
    # reprovações em 7 arquivos, e TODAS são a mesma coisa — o nome do arquivo
    # `CLAUDE.md`, citado por quem escreve sobre as regras da casa
    # (test_portoes_da_casa_estao_ligados_no_ci.py sozinho responde por 19).
    # ZERO são violação de verdade. Devolver o `-i` sem antes decidir o que
    # fazer com esse nome transformaria o portão num gerador de ruído, e a
    # regra da casa é que portão que grita falso é portão que se desliga.
    #
    # A decisão é dela porque é a MESMA decisão do `CLAUDE.md`: o arquivo é
    # proibido de ser versionado por .github/workflows/anonymity-check.yml, e
    # é ela quem escolhe se o NOME dele vira exceção explícita do regex, se o
    # texto passa a citá-lo de outro jeito, ou se o ramo do git segue sensível
    # a maiúscula de propósito. Enquanto não escolher, fica registrado aqui:
    # este ramo NÃO pega o nome de modelo capitalizado.
    #
    # ANONIMATO-BINARIO-FALSO-POSITIVO-01 (01/08/2026): o `-I` NÃO é opcional.
    # Sem ele o `git grep` varre os PNGs de `docs/usage/assets/` e um deles
    # casou o regex POR ACASO, nos bytes comprimidos — a saída era um
    # "Binary file docs/usage/assets/readme_lightbar.png matches" que reprovava
    # o repositório inteiro e não tinha como ser "corrigido", porque não havia
    # texto nenhum ali. E a imagem MUDA a cada `retratar_abas.py`, então o
    # falso positivo é intermitente: aparece e some conforme o desenho da aba.
    #
    # Isto não afrouxa o portão. Ele nunca soube ler imagem: o `README.md` já
    # avisa que os portões de anonimato NÃO varrem imagens, e que a foto da
    # aba Sistema teve de ser borrada à mão. O `-I` só faz o script parar de
    # fingir que varre.
    #
    # A lista entra num array por `read -d ''`, e NÃO por `git ls-files | grep`:
    # é a mesma lição da CORRIDA-DO-PIPEFAIL-01 do check_packaging_parity.sh —
    # produtor num pipe cujo consumidor pode sair antes é corrida, e o
    # `pipefail` do `set -euo pipefail` do topo transformaria o SIGPIPE em
    # veredito.
    ARQUIVOS=()
    while IFS= read -r -d '' _arquivo; do
        ARQUIVOS+=("${_arquivo}")
    done < <(git ls-files -z --cached --others --exclude-standard \
        -- "${EXCLUDE_PATHSPECS[@]}" 2>/dev/null)
    if [[ "${#ARQUIVOS[@]}" -gt 0 ]]; then
        # `2>/dev/null` cobre o caso do arquivo apagado do disco mas ainda no
        # índice, que o `--cached` lista e o grep não acha.
        HITS=$(grep -HnIE "$FORBIDDEN" -- "${ARQUIVOS[@]}" 2>/dev/null || true)
    else
        HITS=""
    fi
else
    # Fallback: grep -r. Limitação: --exclude-dir só aceita basename, então
    # dirs com nome 'process'/'history'/'fixtures' em qualquer nível são excluídos.
    # Recomenda-se git init pra usar o pathspec rico do git grep.
    HITS=$(grep -rnIiE "$FORBIDDEN" . \
        --include="*.py" --include="*.md" --include="*.toml" \
        --include="*.sh" --include="*.yaml" --include="*.yml" \
        --include="*.service" --include="*.rules" \
        --exclude-dir=".git" --exclude-dir="process" \
        --exclude-dir="history" --exclude-dir="fixtures" \
        --exclude="LICENSE" --exclude="NOTICE" --exclude="CHANGELOG.md" \
        --exclude="VALIDATOR_BRIEF.md" --exclude=".gitignore" \
        --exclude="check_anonymity.sh" --exclude="test_check_anonymity.py" \
        --exclude="anonymity-check.yml" \
        2>/dev/null || true)
fi

if [[ -n "$HITS" ]]; then
    echo "ANONIMATO VIOLADO. Remova as referências abaixo:"
    echo "------------------------------------------------"
    echo "$HITS"
    echo "------------------------------------------------"
    echo ""
    echo "Lembrete: LICENSE, NOTICE, CHANGELOG.md, docs/process/**,"
    echo "docs/history/** e tests/fixtures/** estão excluídos do check."
    echo "Decisões de arquitetura com menção de IA devem ficar em"
    echo "docs/process/ (fora do repo) ou docs/history/ (dentro, ignorado)."
    exit 1
fi

echo "OK: anonimato preservado."
exit 0
