#!/usr/bin/env bash
# Verifica anonimato do repo Hefesto - Dualsense4Unix.
# Exit 0 se limpo, exit 1 se houver violação.
# Estratégia: regex completa + whitelist de arquivos (não de palavras).

set -euo pipefail

# Termos proibidos. \b garante palavra inteira onde aplicável.
FORBIDDEN='(\b(claude|anthropic|openai|chatgpt|opus|sonnet|haiku|gemini|copilot|mistral|grok)\b|gpt-?[0-9]+|\bllama[- ]?[0-9]|\bby (claude|ai|gpt|an ai)\b|(ai|machine)-generated|generated by (an? )?(ai|llm|model)|feito por|criado por|autor:\s|made by|written by|credit to)'

# Arquivos/paths excluídos do check. Processo/história, não código.
EXCLUDE_PATHSPECS=(
    ':!LICENSE'
    ':!NOTICE'
    ':!CHANGELOG.md'
    ':!VALIDATOR_BRIEF.md'
    ':!.gitignore'
    ':!docs/process/**'
    ':!docs/history/**'
    ':!tests/fixtures/**'
    ':!tests/unit/test_check_anonymity.py'
    ':!.git/**'
    ':!scripts/check_anonymity.sh'
    # Detector irmão: contém os mesmos regexes (anthropic|openai|claude|...)
    # como parte da própria checagem — auto-referência, não violação.
    ':!.github/workflows/anonymity-check.yml'
)

# Usa git grep se estivermos em repo (respeita .gitignore + pathspec).
# Cai pra grep manual se repo ainda não inicializado (W0.1 pré-git init).
if git rev-parse --git-dir >/dev/null 2>&1; then
    HITS=$(git grep -niE "$FORBIDDEN" -- "${EXCLUDE_PATHSPECS[@]}" 2>/dev/null || true)
else
    # Fallback: grep -r. Limitação: --exclude-dir só aceita basename, então
    # dirs com nome 'process'/'history'/'fixtures' em qualquer nível são excluídos.
    # Recomenda-se git init pra usar o pathspec rico do git grep.
    HITS=$(grep -rniE "$FORBIDDEN" . \
        --include="*.py" --include="*.md" --include="*.toml" \
        --include="*.sh" --include="*.yaml" --include="*.yml" \
        --include="*.service" --include="*.rules" \
        --exclude-dir=".git" --exclude-dir="process" \
        --exclude-dir="history" --exclude-dir="fixtures" \
        --exclude="LICENSE" --exclude="NOTICE" --exclude="CHANGELOG.md" \
        --exclude="VALIDATOR_BRIEF.md" --exclude=".gitignore" \
        --exclude="check_anonymity.sh" --exclude="test_check_anonymity.py" \
        --exclude="anonymity-check.yml" \
        2>/dev/null || true)
fi

if [[ -n "$HITS" ]]; then
    echo "ANONIMATO VIOLADO. Remova as referências abaixo:"
    echo "------------------------------------------------"
    echo "$HITS"
    echo "------------------------------------------------"
    echo ""
    echo "Lembrete: LICENSE, NOTICE, CHANGELOG.md, docs/process/**,"
    echo "docs/history/** e tests/fixtures/** estão excluídos do check."
    echo "Decisões de arquitetura com menção de IA devem ficar em"
    echo "docs/process/ (fora do repo) ou docs/history/ (dentro, ignorado)."
    exit 1
fi

echo "OK: anonimato preservado."
exit 0
