"""Testes de regressão do scripts/check_anonymity.sh.

Usa pytest + subprocess em vez de bats-core para evitar dependência de sistema.
Cada teste monta um repo falso em tmp_path e executa o script contra ele.
"""
from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

import pytest

# Ajuste se o script estiver em outro path relativo ao root do repo.
SCRIPT_REL_PATH = "scripts/check_anonymity.sh"


@pytest.fixture
def fake_repo(tmp_path: Path, request: pytest.FixtureRequest) -> Path:
    """Monta um repo fake mínimo com o script copiado.

    Sem git init: exercita o fallback pra `grep -r` do script.
    Testes que precisam de `git grep` devem adicionar `git init` explícito.
    """
    repo_root = Path(__file__).resolve().parents[2]
    src_script = repo_root / SCRIPT_REL_PATH
    if not src_script.exists():
        pytest.skip(f"script {SCRIPT_REL_PATH} não encontrado no repo")

    # Estrutura mínima que o script espera
    (tmp_path / "scripts").mkdir()
    (tmp_path / "src" / "hefesto_dualsense4unix").mkdir(parents=True)
    (tmp_path / "tests").mkdir()
    (tmp_path / "docs" / "process").mkdir(parents=True)

    dst_script = tmp_path / SCRIPT_REL_PATH
    shutil.copy2(src_script, dst_script)
    dst_script.chmod(0o755)
    return tmp_path


def run_check(repo: Path) -> subprocess.CompletedProcess[str]:
    """Executa o script no cwd do fake repo e captura o resultado."""
    return subprocess.run(
        ["bash", SCRIPT_REL_PATH],
        cwd=repo,
        capture_output=True,
        text=True,
        check=False,
    )


# =============================================================================
# Detecção positiva: o script PRECISA falhar nestes cenários
# =============================================================================

def test_detecta_termo_obvio_em_py(fake_repo: Path) -> None:
    (fake_repo / "src/hefesto_dualsense4unix/modulo.py").write_text("# escrito por claude\n")
    result = run_check(fake_repo)
    assert result.returncode == 1
    assert "ANONIMATO VIOLADO" in result.stdout


def test_detecta_assinatura_pt(fake_repo: Path) -> None:
    (fake_repo / "src/hefesto_dualsense4unix/a.py").write_text("# feito por fulano\n")
    result = run_check(fake_repo)
    assert result.returncode == 1


def test_detecta_assinatura_en(fake_repo: Path) -> None:
    (fake_repo / "src/hefesto_dualsense4unix/a.py").write_text("# written by someone\n")
    result = run_check(fake_repo)
    assert result.returncode == 1


# ANONIMATO-FRONTEIRA-DE-PALAVRA-01 (30/07). O par abaixo trava a fronteira nos
# DOIS sentidos, e por isso são dois testes e não um: sem o `\b`, `feito por`
# casava dentro de "o de|feito por|que" e reprovava o repositório inteiro por uma
# frase legítima; com um `\b` frouxo demais, "feito por uma IA" passaria. O
# defeito real só apareceu DEPOIS do `git add` (o gate usa `git grep` e é cego a
# arquivo não rastreado), então o commit f319c6f entrou vermelho.


def test_frase_legitima_com_defeito_porque_nao_reprova(fake_repo: Path) -> None:
    """"defeito porque" contém "feito por" como substring — e não é assinatura."""
    (fake_repo / "src/hefesto_dualsense4unix/a.py").write_text(
        "# O gate irmão nunca teve o defeito porque o hook chama o script.\n"
        "# E este perfil foi criado porquanto a regra exigia.\n"
    )
    result = run_check(fake_repo)
    assert result.returncode == 0, (
        "substring dentro de outra palavra não é atribuição — o `\\b` do "
        f"FORBIDDEN caiu. Saída: {result.stdout}"
    )


def test_atribuicao_real_continua_reprovando_apos_a_fronteira(fake_repo: Path) -> None:
    """A fronteira não pode ter afrouxado a detecção que o gate existe para fazer."""
    for texto in ("# feito por uma IA\n", "# criado por um modelo\n"):
        (fake_repo / "src/hefesto_dualsense4unix/a.py").write_text(texto)
        result = run_check(fake_repo)
        assert result.returncode == 1, (
            f"atribuição real deixou de reprovar: {texto!r}"
        )


def test_detecta_gpt_com_versao(fake_repo: Path) -> None:
    (fake_repo / "src/hefesto_dualsense4unix/a.py").write_text("# powered by gpt-4\n")
    result = run_check(fake_repo)
    assert result.returncode == 1


def test_detecta_llama_com_versao(fake_repo: Path) -> None:
    (fake_repo / "src/hefesto_dualsense4unix/a.py").write_text("# uses Llama 3\n")
    result = run_check(fake_repo)
    assert result.returncode == 1


def test_detecta_em_markdown(fake_repo: Path) -> None:
    (fake_repo / "README.md").write_text("Generated by an AI.\n")
    result = run_check(fake_repo)
    assert result.returncode == 1


def test_detecta_em_toml(fake_repo: Path) -> None:
    (fake_repo / "pyproject.toml").write_text('authors = ["Autor: anthropic"]\n')
    result = run_check(fake_repo)
    assert result.returncode == 1


# =============================================================================
# Whitelist por arquivo: PRECISA ignorar menções legítimas
# =============================================================================

def test_ignora_license(fake_repo: Path) -> None:
    (fake_repo / "LICENSE").write_text("Copyright notice mentioning Claude.\n")
    result = run_check(fake_repo)
    assert result.returncode == 0, result.stdout


def test_ignora_notice(fake_repo: Path) -> None:
    (fake_repo / "NOTICE").write_text("Derived from pydualsense by claude.\n")
    result = run_check(fake_repo)
    assert result.returncode == 0, result.stdout


def test_ignora_changelog(fake_repo: Path) -> None:
    (fake_repo / "CHANGELOG.md").write_text("- generated by an llm (anotado)\n")
    result = run_check(fake_repo)
    assert result.returncode == 0, result.stdout


def test_ignora_docs_process(fake_repo: Path) -> None:
    (fake_repo / "docs/process/DECISIONS_V2.md").write_text(
        "Discussão com Claude sobre arquitetura.\n"
    )
    result = run_check(fake_repo)
    assert result.returncode == 0, result.stdout


def test_ignora_tests_fixtures(fake_repo: Path) -> None:
    (fake_repo / "tests" / "fixtures").mkdir()
    (fake_repo / "tests/fixtures/sample.py").write_text(
        "# dados de teste com claude como valor\n"
    )
    result = run_check(fake_repo)
    assert result.returncode == 0, result.stdout


# =============================================================================
# Falsos positivos conhecidos: NÃO pode disparar em usos legítimos
# =============================================================================

def test_nao_falsa_em_palavra_model(fake_repo: Path) -> None:
    """'model' é palavra genérica — não deve casar com regex de modelos de IA."""
    (fake_repo / "src/hefesto_dualsense4unix/a.py").write_text(
        "model_name = 'DualSense'\n"
        "def build_model(params): pass\n"
    )
    result = run_check(fake_repo)
    assert result.returncode == 0, result.stdout


def test_nao_falsa_em_llama_cpp(fake_repo: Path) -> None:
    """Regex exige dígito após llama: 'llama-cpp' não casa, 'Llama 3' sim."""
    (fake_repo / "src/hefesto_dualsense4unix/a.py").write_text(
        "# integra com llama-cpp-python se disponível\n"
    )
    result = run_check(fake_repo)
    assert result.returncode == 0, result.stdout


def test_nao_falsa_no_codec_opus(fake_repo: Path) -> None:
    """ANONIMATO-FALSO-POSITIVO-OPUS-01: `opus` sozinho NÃO reprova mais.

    O "contexto legítimo" que a versão anterior deste teste previa como
    hipotético chegou: Opus é o codec de áudio da IETF (RFC 6716), e é o que
    o DualSense usa para o microfone e o fone por Bluetooth. A palavra virou
    vocabulário obrigatório do projeto — barrá-la reprovava código honesto e
    empurrava a documentação do protocolo para eufemismo.

    O gate não perdeu alcance: o uso que ele existe para barrar é o de NOME DE
    MODELO, e esse nunca vem sozinho.
    """
    (fake_repo / "src/hefesto_dualsense4unix/a.py").write_text(
        "# frame do codec Opus: 71 bytes, mono, 48 kHz\n"
    )
    result = run_check(fake_repo)
    assert result.returncode == 0, result.stdout


def test_ainda_pega_o_modelo_composto(fake_repo: Path) -> None:
    """A contraparte: liberar o codec não pode abrir a porta para o modelo."""
    (fake_repo / "src/hefesto_dualsense4unix/a.py").write_text(
        "# escrito com Claude Opus\n"
    )
    result = run_check(fake_repo)
    assert result.returncode == 1, result.stdout


def test_nao_falsa_em_termos_tecnicos_en(fake_repo: Path) -> None:
    """Termos EN técnicos preservados pela convenção de idioma não disparam."""
    (fake_repo / "src/hefesto_dualsense4unix/a.py").write_text(
        'logger.error("falha ao ler hidraw: Permission denied")\n'
        'logger.warn("pacote UDP descartado: version desconhecida")\n'
    )
    result = run_check(fake_repo)
    assert result.returncode == 0, result.stdout


# =============================================================================
# Auto-exclusão: o próprio script não pode gatilhar em si mesmo
# =============================================================================

def test_script_nao_dispara_em_si_mesmo(fake_repo: Path) -> None:
    """Script tem o próprio path na whitelist. Verifica que não detecta
    as próprias strings da regex como violação."""
    result = run_check(fake_repo)
    assert result.returncode == 0, result.stdout


# =============================================================================
# Modo git: verifica caminho alternativo quando repo está inicializado
# =============================================================================

def test_funciona_com_git_grep(fake_repo: Path) -> None:
    """Quando em repo git, usa git grep com pathspec exclude."""
    subprocess.run(["git", "init"], cwd=fake_repo, check=True, capture_output=True)
    subprocess.run(
        ["git", "config", "user.email", "test@example.com"],
        cwd=fake_repo, check=True, capture_output=True,
    )
    subprocess.run(
        ["git", "config", "user.name", "test"],
        cwd=fake_repo, check=True, capture_output=True,
    )

    (fake_repo / "src/hefesto_dualsense4unix/a.py").write_text("# código limpo\n")
    subprocess.run(["git", "add", "."], cwd=fake_repo, check=True, capture_output=True)

    result = run_check(fake_repo)
    assert result.returncode == 0, result.stdout


def test_git_grep_detecta_violacao_rastreada(fake_repo: Path) -> None:
    """Arquivo commitado com violação é detectado via git grep."""
    subprocess.run(["git", "init"], cwd=fake_repo, check=True, capture_output=True)
    subprocess.run(
        ["git", "config", "user.email", "test@example.com"],
        cwd=fake_repo, check=True, capture_output=True,
    )
    subprocess.run(
        ["git", "config", "user.name", "test"],
        cwd=fake_repo, check=True, capture_output=True,
    )

    (fake_repo / "src/hefesto_dualsense4unix/a.py").write_text("# by claude\n")
    subprocess.run(["git", "add", "."], cwd=fake_repo, check=True, capture_output=True)

    result = run_check(fake_repo)
    assert result.returncode == 1


# =============================================================================
# ANONIMATO-CEGO-A-ARQUIVO-NOVO-01 e ANONIMATO-MAIUSCULA-01 (13/08/2026)
#
# Os dois furos que o ramo do git tinha e a suíte não via, porque TODO teste
# acima ou roda o ramo de fallback (sem `git init`) ou faz `git add` antes de
# medir. Ambos foram medidos num repo de mentira em 13/08/2026, e ambos davam
# "OK: anonimato preservado." com exit 0.
# =============================================================================

def _git_de_mentira(repo: Path) -> None:
    """Inicializa o repo fake para que o script tome o ramo do git."""
    subprocess.run(["git", "init"], cwd=repo, check=True, capture_output=True)
    subprocess.run(
        ["git", "config", "user.email", "test@example.com"],
        cwd=repo, check=True, capture_output=True,
    )
    subprocess.run(
        ["git", "config", "user.name", "test"],
        cwd=repo, check=True, capture_output=True,
    )


def test_git_detecta_violacao_em_arquivo_ainda_nao_adicionado(fake_repo: Path) -> None:
    """O portão enxerga o arquivo NOVO, antes de qualquer `git add`.

    Com `git grep` este cenário passava verde: `git grep` só lê o índice, e o
    arquivo que ninguém revisou é justamente o que ainda não foi adicionado.
    A cura é `git ls-files --cached --others --exclude-standard`, o mesmo
    remédio que `validar-acentuacao.py` e `validar-glifos.py` já tomaram.
    """
    _git_de_mentira(fake_repo)
    (fake_repo / "src/hefesto_dualsense4unix/a.py").write_text("# código limpo\n")
    subprocess.run(["git", "add", "."], cwd=fake_repo, check=True, capture_output=True)

    # Este NUNCA passa por `git add` — é o arquivo recém-escrito.
    (fake_repo / "src/hefesto_dualsense4unix/novo.py").write_text("# by claude\n")

    result = run_check(fake_repo)
    assert result.returncode == 1, (
        "arquivo novo com violação passou VERDE: o portão voltou a olhar só o "
        f"índice.\nsaída:\n{result.stdout}"
    )
    assert "novo.py" in result.stdout, result.stdout


def test_git_nao_reprova_arquivo_novo_que_o_gitignore_manda_ignorar(
    fake_repo: Path,
) -> None:
    """A outra metade da régua: `--exclude-standard` não pode ser esquecido.

    Sem ele a cura acima traria o que o `.gitignore` manda ignorar — build,
    `.venv`, capturas — e o portão passaria a reprovar coisa que não é da
    árvore. Um portão que grita falso é um portão desligado.
    """
    _git_de_mentira(fake_repo)
    (fake_repo / ".gitignore").write_text("lixo/\n", encoding="utf-8")
    (fake_repo / "lixo").mkdir()
    (fake_repo / "lixo" / "gerado.py").write_text("# by claude\n")

    result = run_check(fake_repo)
    assert result.returncode == 0, result.stdout


# =============================================================================
# ANONIMATO-MAIUSCULA-01 (achado 13/08/2026, curado 26/08/2026)
#
# O ramo do GIT não levava `-i`, e a regex do script é toda minúscula. Ninguém
# escreve nome próprio em minúscula, então maiúscula era esconderijo — e a
# suíte não via, porque `test_ainda_pega_o_modelo_composto` (lá em cima)
# exercita o ramo de FALLBACK, que nunca perdeu o `-i`.
#
# Por isso TODO teste desta seção chama `_git_de_mentira` e faz `git add`: é o
# ramo do `grep -HnIiE` da linha ~144 que está sob a régua, e nenhum outro.
# =============================================================================

def test_maiuscula_nao_e_esconderijo(fake_repo: Path) -> None:
    """Nome de modelo capitalizado reprova NO RAMO DO GIT, não só no fallback."""
    _git_de_mentira(fake_repo)
    (fake_repo / "src/hefesto_dualsense4unix/a.py").write_text(
        "# Escrito com Claude Opus.\n"
    )
    subprocess.run(["git", "add", "."], cwd=fake_repo, check=True, capture_output=True)

    result = run_check(fake_repo)
    assert result.returncode == 1, (
        "maiúscula passou verde no ramo do git: o `-i` do grep sumiu de novo.\n"
        f"saída:\n{result.stdout}"
    )
    assert "a.py" in result.stdout, result.stdout


def test_maiuscula_de_provedor_nao_e_esconderijo(fake_repo: Path) -> None:
    """A segunda forma medida: o nome do provedor, também capitalizado."""
    _git_de_mentira(fake_repo)
    (fake_repo / "src/hefesto_dualsense4unix/a.py").write_text(
        "# Feito na Anthropic.\n"
    )
    subprocess.run(["git", "add", "."], cwd=fake_repo, check=True, capture_output=True)

    result = run_check(fake_repo)
    assert result.returncode == 1, result.stdout


def test_o_nome_do_arquivo_de_regras_nao_e_violacao(fake_repo: Path) -> None:
    """Primeira família do ruído medido: o literal `CLAUDE.md`.

    São 56 acusações em 26 arquivos desta árvore, todas citações do NOME de um
    arquivo por quem escreve sobre as regras da casa. O arquivo é proibido de
    ser versionado; o nome dele, não.
    """
    _git_de_mentira(fake_repo)
    (fake_repo / "src/hefesto_dualsense4unix/a.py").write_text(
        "# a regra está no `CLAUDE.md`, bloco 'As regras desta casa'\n"
    )
    subprocess.run(["git", "add", "."], cwd=fake_repo, check=True, capture_output=True)

    result = run_check(fake_repo)
    assert result.returncode == 0, (
        "o portão virou gerador de ruído: o nome do arquivo de regras não é "
        f"violação.\nsaída:\n{result.stdout}"
    )


def test_atribuicao_a_uma_pessoa_nao_e_violacao(fake_repo: Path) -> None:
    """Segunda família: `feito por ela` é atribuição a uma PESSOA."""
    _git_de_mentira(fake_repo)
    (fake_repo / "src/hefesto_dualsense4unix/a.py").write_text(
        "# O par foi feito POR ELA, fechando a Steam no meio.\n"
    )
    subprocess.run(["git", "add", "."], cwd=fake_repo, check=True, capture_output=True)

    result = run_check(fake_repo)
    assert result.returncode == 0, result.stdout


def test_a_isencao_e_por_casamento_e_nao_por_linha(fake_repo: Path) -> None:
    """A mordida que separa a cura certa da cura preguiçosa.

    Um `grep -v` descartaria a LINHA inteira, e a violação de verdade sairia de
    carona com o ruído. A isenção apaga só o TRECHO isento e pergunta de novo.
    """
    _git_de_mentira(fake_repo)
    (fake_repo / "src/hefesto_dualsense4unix/a.py").write_text(
        "# Escrito com Claude Opus — ver `CLAUDE.md`\n"
    )
    subprocess.run(["git", "add", "."], cwd=fake_repo, check=True, capture_output=True)

    result = run_check(fake_repo)
    assert result.returncode == 1, (
        "violação real escondida atrás do ruído isento: a isenção está "
        f"descartando a LINHA em vez do CASAMENTO.\nsaída:\n{result.stdout}"
    )


def test_atribuicao_a_uma_ia_continua_reprovando(fake_repo: Path) -> None:
    """A contraparte de `feito por ela`: o `\\bfeito por\\b` não foi afrouxado."""
    _git_de_mentira(fake_repo)
    (fake_repo / "src/hefesto_dualsense4unix/a.py").write_text(
        "# Feito por uma IA.\n"
    )
    subprocess.run(["git", "add", "."], cwd=fake_repo, check=True, capture_output=True)

    result = run_check(fake_repo)
    assert result.returncode == 1, result.stdout
